// Mock in-memory data for running without database
import bcrypt from 'bcrypt'

const passwordHash = bcrypt.hashSync('password123', 10)

export const mockGallery = {
  id: 'gal_ceqnce',
  name: 'Ceqnce Contemporary',
  contactEmail: 'info@ceqnce.com',
}

export const mockUsers = [
  {
    id: 'user_jane',
    galleryId: 'gal_ceqnce',
    name: 'Jane Alvarez',
    email: 'jane@ceqnce.com',
    role: 'GALLERY_ADMIN',
    passwordHash,
  },
  {
    id: 'user_marc',
    galleryId: 'gal_ceqnce',
    name: 'Marc Liu',
    email: 'marc@ceqnce.com',
    role: 'SPECIALIST',
    passwordHash,
  },
]

export const mockObjects = [
  {
    id: 'obj_blue_composition',
    galleryId: 'gal_ceqnce',
    title: 'Blue Composition',
    artist: 'Lea Richter',
    year: 2019,
    medium: 'Acrylic on canvas',
    dimensions: '120 x 90 cm',
    location: 'Main Gallery',
    price: 8500000, // $85,000 in cents
    status: 'AVAILABLE',
    imageUrl: '/images/blue-composition.jpg',
    metadataJson: {
      style: 'Abstract',
      palette: ['blue', 'white', 'black'],
      notes: "Part of the 'Tidal Forms' series.",
    },
  },
  {
    id: 'obj_city_dreams',
    galleryId: 'gal_ceqnce',
    title: 'City Dreams',
    artist: 'Rafael Ortega',
    year: 2015,
    medium: 'Oil on canvas',
    dimensions: '100 x 80 cm',
    location: 'Viewing Room',
    price: 12000000,
    status: 'AVAILABLE',
    imageUrl: '/images/city-dreams.jpg',
    metadataJson: { style: 'Figurative', theme: 'Urban landscape' },
  },
  {
    id: 'obj_neon_grid',
    galleryId: 'gal_ceqnce',
    title: 'Neon Grid',
    artist: 'Aya Nakamoto',
    year: 2022,
    medium: 'LED, plexiglass',
    dimensions: '180 x 180 cm',
    location: 'Storage',
    price: 6000000,
    status: 'ON_HOLD',
    imageUrl: '/images/neon-grid.jpg',
    metadataJson: { style: 'Light sculpture', series: 'Electric Fields' },
  },
  {
    id: 'obj_morning_study',
    galleryId: 'gal_ceqnce',
    title: 'Morning Study',
    artist: 'Clara Jensen',
    year: 1973,
    medium: 'Watercolor on paper',
    dimensions: '40 x 30 cm',
    location: 'Secondary Market Room',
    price: 4500000,
    status: 'CONSIGNED',
    imageUrl: '/images/morning-study.jpg',
    metadataJson: { style: 'Modern', provenance: 'Private collection, Zurich' },
  },
]

export const mockClients = [
  {
    id: 'client_robin',
    galleryId: 'gal_ceqnce',
    name: 'Robin Patel',
    email: 'robin.patel@example.com',
    phone: '+1 212 555 0198',
    typeTags: 'BUYER',
    knownInterests: 'Post-2000 abstract painting; blue palettes; large-scale wall works.',
    digitalEngagementJson: {
      websiteVisitsLast90Days: 7,
      lastVisitedArtists: ['Lea Richter', 'Aya Nakamoto'],
      emailOpensLast30Days: 5,
      lastCampaignsOpened: ['Spring Abstracts', 'New Light Works'],
    },
    pastBuyingEngagementJson: {
      totalSpend: 210000,
      currency: 'USD',
      lastPurchase: { title: 'Tidal Form #3', artist: 'Lea Richter', year: 2018, price: 90000 },
      budgetRange: { min: 50000, max: 150000 },
    },
  },
  {
    id: 'client_sophia',
    galleryId: 'gal_ceqnce',
    name: 'Sophia Klein',
    email: 'sophia.klein@example.com',
    phone: '+44 20 5550 1111',
    typeTags: 'BUYER,CONSIGNER',
    knownInterests: 'Modern European works on paper; 1960s–1980s; works with strong provenance.',
    digitalEngagementJson: {
      websiteVisitsLast90Days: 3,
      lastVisitedArtists: ['Clara Jensen'],
      emailOpensLast30Days: 2,
    },
    pastBuyingEngagementJson: {
      totalSpend: 95000,
      currency: 'USD',
      lastPurchase: { title: 'Winter Garden', artist: 'Clara Jensen', year: 1970, price: 35000 },
      budgetRange: { min: 30000, max: 80000 },
    },
  },
  {
    id: 'client_marcus',
    galleryId: 'gal_ceqnce',
    name: 'Marcus de la Cruz',
    email: 'marcus.dlc@example.com',
    phone: '+34 91 555 2222',
    typeTags: 'BUYER',
    knownInterests: 'Latin American figurative painting; urban scenes; 50–120k.',
    digitalEngagementJson: {
      websiteVisitsLast90Days: 5,
      lastVisitedArtists: ['Rafael Ortega'],
      emailOpensLast30Days: 4,
    },
    pastBuyingEngagementJson: {
      totalSpend: 150000,
      currency: 'USD',
      budgetRange: { min: 50000, max: 120000 },
    },
  },
  {
    id: 'client_anna',
    galleryId: 'gal_ceqnce',
    name: 'Anna Weiss',
    email: 'anna.weiss@example.com',
    phone: '+41 44 555 3333',
    typeTags: 'CONSIGNER',
    knownInterests: 'Previously collected modern Scandinavian works; now selectively selling.',
    digitalEngagementJson: {
      websiteVisitsLast90Days: 1,
      emailOpensLast30Days: 1,
    },
    pastBuyingEngagementJson: {
      totalSpend: 0,
      currency: 'USD',
    },
  },
]

export const mockDealFlows = [
  {
    id: 'deal_object_sale_blue_comp',
    galleryId: 'gal_ceqnce',
    type: 'OBJECT_SALE',
    status: 'QUALIFYING',
    title: 'Blue Composition – Priority Buyer Outreach',
    description: "Identify and prioritize likely buyers for Lea Richter's 'Blue Composition' and coordinate outreach.",
    objectId: 'obj_blue_composition',
    clientId: null,
    metadataJson: { priority: 'high', targetCloseDate: '2024-03-31' },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'deal_client_request_marcus',
    galleryId: 'gal_ceqnce',
    type: 'CLIENT_REQUEST',
    status: 'IN_PROGRESS',
    title: 'Marcus – Latin American urban figurative work',
    description: 'Marcus is looking for a Latin American figurative painting with urban subject matter between 50–120k.',
    objectId: null,
    clientId: 'client_marcus',
    metadataJson: { budgetMin: 50000, budgetMax: 120000, preferredArtists: ['Rafael Ortega'] },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'deal_consignment_sophia_jensen',
    galleryId: 'gal_ceqnce',
    type: 'CONSIGNMENT',
    status: 'INFO_GATHERING',
    title: 'Sophia – Jensen watercolor consignment',
    description: "Evaluate and potentially consign 'Morning Study' by Clara Jensen for sale in 2024.",
    objectId: 'obj_morning_study',
    clientId: 'client_sophia',
    metadataJson: {
      targetValuationDate: '2024-02-15',
      possibleSaleChannels: ['Private sale', 'Fair'],
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
  },
]

export const mockClientNotes = [
  {
    id: 'note_1',
    clientId: 'client_robin',
    specialistId: 'user_jane',
    type: 'TEXT',
    text: 'Very responsive to email; prefers works that feel calm and atmospheric. Likes blue/green palettes.',
    tags: 'preferences,tone',
    linkedObjectId: 'obj_blue_composition',
    linkedDealFlowId: null,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'note_2',
    clientId: 'client_sophia',
    specialistId: 'user_marc',
    type: 'TEXT',
    text: "Considering selling 'Morning Study' and one other Jensen work. Wants valuation by March.",
    tags: 'consignment,valuation',
    linkedObjectId: 'obj_morning_study',
    linkedDealFlowId: 'deal_consignment_sophia_jensen',
    createdAt: new Date('2024-01-08'),
  },
]

export const mockExternalInventory = [
  {
    id: 'extitem_latin_auction',
    sourceType: 'AUCTION_HOUSE',
    sourceName: 'Casa del Arte Auctions',
    contactName: 'Lucia Romero',
    contactEmail: 'lucia.romero@casadelarte.com',
    contactPhone: '+34 93 555 7777',
    objectTitle: 'Nocturne in Red',
    artist: 'Rafael Ortega',
    year: 2014,
    medium: 'Oil on canvas',
    priceInfo: 'Estimate 80,000–110,000 USD',
    metadataJson: { style: 'Figurative', theme: 'Urban night scene', saleDate: '2024-03-15' },
  },
  {
    id: 'extitem_jensen_drawing',
    sourceType: 'GALLERY',
    sourceName: 'Nordic Lines',
    contactName: 'Erik Lund',
    contactEmail: 'erik@nordiclines.com',
    contactPhone: '+46 8 555 9999',
    objectTitle: 'Summer Sketch',
    artist: 'Clara Jensen',
    year: 1971,
    medium: 'Pencil and watercolor on paper',
    priceInfo: 'Asking 38,000 USD',
    metadataJson: { provenance: 'Private collection, Stockholm' },
  },
]
